### ISSUE TITLE
Support calendars other than Calendar.ISO

### ISSUE THREAD

**Issue by kipcole9** [wojtekmach/calendar_interval#5]
As I think you know, I have a package that [provides calendars other than `Calendar.ISO`](https://github.com/elixir-cldr/cldr_calendars).  Would you consider a PR that adds support for non `Calendar.ISO` calendars to `calendar_interval`?

I can see if would require a bit of refactoring but I don't think anything especially traumatic.

**Comment by LostKobrakai** [comment]
I really like the idea of different calendars. I'd just like to see e.g. protocols or another optional way for sloting in other calendars. Setting up cldr is quite a lot to ask for if it's data is not really needed, so `calendar_interval` should probably work with and without it.

**Comment by wojtekmach** [comment]
Supporting different calendars sounds great, but I'm not sure about the implementation. I have pretty limited time right now, so let's talk after ElixirConf (or on the conference if you happen to be there!)

**Comment by kipcole9** [comment]
Completely agree, `calendar_interval` (and `calendar_recurrence`) should operate independent of any calendar implementation.

The `Calendar` `behaviour` doesn't provide the coverage to make this work and I like the idea of considering whether a protocol-based approach will work.  That would also allow an implementation for `Calendar.ISO` without touching the core.

I won't be at elixirconf and I will be on a bunch of long flights so I'll investigate.

@wojtekmach I wasn't for a moment trying to suggest *you* do this, I'm fine to work on it.  Just want to see if that was ok with you.

**Comment by kipcole9** [comment]
I've sent a [PR](https://github.com/wojtekmach/calendar_interval/pull/6) to support calendars other than `Calendar.ISO`.

**Comment by kipcole9** [comment]
Updated the PR with support for a precision of `:quarter`.

**Comment by wojtekmach** [comment]
Closing in favour of PR #6.
